SELECT *
FROM
  (SELECT C.UF,
    COUNT(1)      AS QUANTIDADE_APOSTAS,
    SUM(AP.VALOR) AS VALOR_ARRECADADO
  FROM APOSTA AP
  INNER JOIN CIDADE C
  ON AP.IDCIDADE      = C.IDCIDADE
  WHERE AP.IDCONCURSO = 1824
  GROUP BY C.UF
  ORDER BY VALOR_ARRECADADO DESC
  )
WHERE ROWNUM <= 5;